### ISSUE TITLE
Outdated docker images (maybe caused by some failing GitHub actions)

### ISSUE THREAD

**Issue by dotWee** [sebbo2002/pyatv-mqtt-bridge#189]
## Outdated Docker Images

By accident i discovered that your published docker images are pretty much all outdated, except the version for `amd64`.

The `:latest` tag is missing the `armv6`, `armv7` & `arm64`/`aarch64` platform images and the last `armXY` image is older than a year.

I'm guessing the failed ci buils went under your radar: https://github.com/sebbo2002/pyatv-mqtt-bridge/actions/runs/3129789032

Not sure why they are failing exactly tho, as I'm able to build the images without any issues from develop branch.  

Built with `$ docker buildx build --platform linux/arm64,linux/amd64,linux/arm/v7 --tag dotwee/pyatv-mqtt-bridge:latest .` and tested `arm64` successfully.

![Screenshot 2022-10-01 at 02 29 59](https://user-images.githubusercontent.com/8060356/193376321-ccc4cc78-7bf3-4bc7-a49c-535cfe75a9b2.png)

**Comment by sebbo2002** [comment]
Hi, you can ignore the two annotations as long as the build did not fail. The workflow is designed to repeat the build up to 3x if something goes wrong (as in this case). [On GitHub](https://github.com/sebbo2002/pyatv-mqtt-bridge/pkgs/container/pyatv-mqtt-bridge/43215699?tag=7621017f9a3470db17c6e97b75c6943ad83a7871) is at least amd64, arm64 and armv7, I guess the rest are missing corresponding containers. But I'll check later why they are not on DockerHub.

**Comment by sebbo2002** [comment]
Short update on this: On DockerHub, at least the images which are tagged with a git sha are correct multi platform images. What is still missing are the latest/next tags. The problem here is that these are created with `docker pull / docker tag / docker push`, which does not work with multi-platform images. Accordingly, this is a bit of a major rebuild that I can only tackle when I find the time. But until then you can use these tags or you can use the Docker images from GitHub directly.

**Comment by sebbo2002** [comment]
Should be fixed, thank you

**Comment by dotWee** [comment]
Not fully sure why you had issues with publishing multiplatform docker images.

But i only have experience using directly multiarch building & pushing without going through `docker pull / docker tag / docker push`.

If you're still thinking about a major rebuild of your Docker GitHub CI, maybe check out the [docker/metadata](https://github.com/docker/metadata-action) action to remove complexity.  
Running multiple docker-build with the same metadata shouldn't be necessary.

**Comment by sebbo2002** [comment]
I have only docker-build several times, because unfortunately there is no easy way to automatically retry the build in case of errors. At least I don't know of one, if there is I would appreciate a hint. Since the version is formed only after the image build within semantic-release, the tags are not yet fixed at build. Therefore I decided to use this way. If you know a nicer way to tag docker images with semantic-release, also happy to say something.
